Lumle.Web/Components/LoginStatusViewComponent.cs
using Lumle.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace Lumle.Web.Components
{
    public class LoginStatusViewComponent : ViewComponent
    {
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public LoginStatusViewComponent(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            try
            {
                if (_signInManager.IsSignedIn(HttpContext.User))
                {
                    var user = await _userManager.GetUserAsync(HttpContext.User);
                    return View("LoggedIn", user);
                }
                else
                {
                    return View();
                }
            }
            catch(Exception ex)
            {
                return Content(ex.Message);
            }
         
        }
    }
}

Lumle.Web/Views/Shared/404.cshtml
@{
    Layout = "_Layout";
}

<h1 class="text-danger">We are sorry!</h1>
<h2 class="text-danger">The page you have requested cannot be found</h2>
<p>Maybe the page was moved or deleted, or perhaps you just mistyped the address.</p>
<p>Why not try and find your way using the navigation bar above or click on the logo to return our home page.</p>

Lumle.Web/Views/Shared/Maintainance.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = Localizer[LabelConstants.SystemUnderMaintenanceMode];
}

<div class="center-vertical">
    <div class="center-content row">
        <div class="col-md-6 center-margin">
            <div class="server-message wow bounceInDown inverse">
                <h1 style="margin-top:10%;">@Localizer[LabelConstants.SystemUnderMaintenanceMode]</h1>
                <p>@Localizer[LabelConstants.SystemUnderMaintenanceModeMessage]</p>
            </div>
        </div>
    </div>
</div>

Lumle.Web/Views/Shared/_ApplicationScriptPartial.cshtml
<!--All application min-js  refrences-->

<script type="text/javascript" src="~/assets/js-core/jquery-core.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/jquery-ui-core.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/jquery-ui-widget.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/jquery-ui-mouse.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/jquery-ui-position.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/modernizr.min.js"></script>
<script type="text/javascript" src="~/assets/js-core/jquery-cookie.min.js"></script>
<!-- WIDGETS -->
<script type="text/javascript" src="~/assets/bootstrap/js/bootstrap.min.js"></script>
<!-- Bootstrap Progress Bar -->
<script type="text/javascript" src="~/assets/widgets/progressbar/progressbar.min.js"></script>
<!-- Superclick -->
<script type="text/javascript" src="~/assets/widgets/superclick/superclick.min.js"></script>
<!-- Input switch alternate -->
<script type="text/javascript" src="~/assets/widgets/input-switch/inputswitch-alt.min.js"></script>
<!-- Slim scroll -->
<script type="text/javascript" src="~/assets/widgets/slimscroll/slimscroll.min.js"></script>
<!-- Slidebars -->
<script type="text/javascript" src="~/assets/widgets/slidebars/slidebars.min.js"></script>
<script type="text/javascript" src="~/assets/widgets/slidebars/slidebars-demo.min.js"></script>
<!-- Screenfull -->
<script type="text/javascript" src="~/assets/widgets/screenfull/screenfull.min.js"></script>
<!-- Content box -->
<script type="text/javascript" src="~/assets/widgets/content-box/contentbox.min.js"></script>
<!-- Overlay -->
<script type="text/javascript" src="~/assets/widgets/overlay/overlay.min.js"></script>
<!-- Theme layout -->
<script type="text/javascript" src="~/assets/themes/admin/layout.min.js"></script>

<script type="text/javascript" src="~/js/change-language.min.js"></script>

Lumle.Web/Views/Shared/_ApplicationStylesPartial.cshtml
<link rel="stylesheet" type="text/css" href="~/assets/bootstrap/css/bootstrap.min.css">
<!-- HELPERS -->                             
<link rel="stylesheet" type="text/css" href="~/assets/helpers/backgrounds.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/helpers/boilerplate.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/helpers/spacing.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/helpers/utils.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/helpers/colors.min.css">
<!-- ELEMENTS -->                            
<link rel="stylesheet" type="text/css" href="~/assets/elements/buttons.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/content-box.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/dashboard-box.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/forms.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/menus.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/response-messages.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/elements/timeline.min.css">
<!-- ICONS -->                               
<link rel="stylesheet" type="text/css" href="~/assets/icons/fontawesome/fontawesome.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/icons/linecons/linecons.min.css">
<!-- WIDGETS -->                             
<link rel="stylesheet" type="text/css" href="~/assets/widgets/accordion-ui/accordion.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/widgets/dialog/dialog.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/widgets/dropdown/dropdown.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/widgets/modal/modal.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/widgets/slidebars/slidebars.min.css">
<!-- SNIPPETS -->                            
<link rel="stylesheet" type="text/css" href="~/assets/snippets/login-box.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/snippets/user-profile.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/snippets/mobile-navigation.min.css">

<!-- APPLICATIONS -->                        
<!-- Admin theme -->                         
<link rel="stylesheet" type="text/css" href="~/assets/themes/admin/layout.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/themes/admin/color-schemes/default.min.css">
<!-- Components theme -->                    
<link rel="stylesheet" type="text/css" href="~/assets/themes/components/default.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/themes/components/border-radius.min.css">
<!-- Admin responsive -->                    
<link rel="stylesheet" type="text/css" href="~/assets/helpers/responsive-elements.min.css">
<link rel="stylesheet" type="text/css" href="~/assets/helpers/admin-responsive.min.css">
<link rel="stylesheet" type="text/css" href="~/css/custom.css" />

Lumle.Web/Views/Shared/_FELayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>@ViewData["Title"]</title>

    <!-- new style refrences start -->
    <!-- HELPERS -->
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/backgrounds.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/boilerplate.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/grid.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/spacing.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/utils.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/colors.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/typography.min.css">
    <!-- ELEMENTS -->
    <link rel="stylesheet" type="text/css" href="~/assets/elements/buttons.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/elements/content-box.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/elements/forms.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/elements/response-messages.min.css">
    <!-- FRONTEND ELEMENTS -->
    <link rel="stylesheet" type="text/css" href="~/assets/frontend-elements/footer.min.css">
    <!--WIDGETS-->
    <link rel="stylesheet" type="text/css" href="~/assets/widgets/dialog/dialog.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/widgets/dropdown/dropdown.min.css">
    <!-- ICONS -->
    <link rel="stylesheet" type="text/css" href="~/assets/icons/fontawesome/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/widgets/fullpage/fullpage.min.css">
    <!-- SNIPPETS -->
    <link rel="stylesheet" type="text/css" href="~/assets/snippets/login-box.min.css">
    <!-- Frontend theme -->
    <link rel="stylesheet" type="text/css" href="~/assets/themes/frontend/layout.css">
    <link rel="stylesheet" type="text/css" href="~/assets/themes/frontend/color-schemes/default.min.css">
    <!-- Frontend responsive -->
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/responsive-elements.min.css">
    <link rel="stylesheet" type="text/css" href="~/assets/helpers/frontend-responsive.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/homescreen-custom.css" />

    @RenderSection("styles", required: false)
    <!-- JS Core -->

    <script type="text/javascript" src="~/assets/js-core/jquery-core.min.js"></script>
    <script type="text/javascript" src="~/assets/js-core/jquery-ui-core.min.js"></script>

    <script type="text/javascript">
        $(window).load(function () {
            setTimeout(function () {
                $('#loading').fadeOut(400, "linear");
            }, 300);
        });
    </script>
</head>
<body class="body-alt">
    @*<link href="http://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet" type="text/css">*@
    <div id="loading">
        <div class="spinner">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
    <div id="page-wrapper">
        <div class="main-header header-fixed font-inverse header-opacity header-resizable wow bounceInDown" data-0="padding: 35px 0; background: rgba(255,255,255,0.1);" data-250="padding: 0px 0; background: rgba(0,0,0,1)">
            <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="header-logo" title="Lumle CMS"></a>
                <!-- .header-logo -->
                <ul class="header-nav collapse">
                    <vc:login-status></vc:login-status>
                </ul>

            </div><!-- .container -->
        </div><!-- .main-header -->

    </div>
    @RenderBody()

</body>
</html>

<!-- Fullpage.js -->
<script type="text/javascript" src="~/assets/widgets/fullpage/fullpage.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#fullpage').fullpage({
            anchors: ['firstPage'],
            autoScrolling: false,
            css3: true
        });
    });
</script>


@RenderSection("scripts", required: false)

Lumle.Web/Views/Shared/_Layout.cshtml
@using Lumle.Infrastructure.Models
@inject IOptionsSnapshot<LumleSettings> settings

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lumle</title>

    <!-- Favicons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/assets/images/icons/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/assets/images/icons/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/assets/images/icons/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/assets/images/icons/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="~/assets/images/icons/favicon.png">
    
    @Html.Partial("_ApplicationStylesPartial")

    @RenderSection("styles", required: false)

</head>

<body>
    <div id="sb-site">
        <div id="page-wrapper">
            <div id="page-header" class="bg-gradient-9">
                <div id="mobile-navigation">
                    <button id="nav-toggle" class="collapsed" data-toggle="collapse" data-target="#page-sidebar"><span></span></button>
                    <a asp-area="" asp-controller="Account" asp-action="Index" class="logo-content-small" title="Lumle CMS"></a>
                </div>
                <div id="header-logo" class="logo-bg">
                    <a asp-area="" asp-controller="Account" asp-action="Index" class="logo-content-big" title="Lumle CMS">
                        Lumle <i>CMS</i>
                    </a>
                    <a asp-area="" asp-controller="Account" asp-action="Index" class="logo-content-small">
                        Lumle <i>CMS</i>
                    </a>
                    <a id="close-sidebar" href="#" title="Close sidebar">
                        <i class="glyph-icon icon-angle-left"></i>
                    </a>
                </div>
                <div id="header-nav-left">
                    @await Html.PartialAsync("_UserProfilePartial")
                </div><!-- #header-nav-left -->

                <div id="header-nav-right">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>

            </div>

            <div id="page-sidebar">
                <!-- SideBar loaded through SideBar View Component -->
                <vc:side-bar></vc:side-bar>
            </div>

            <div id="page-content-wrapper">
                <div id="page-content">                
                        @RenderBody()
                </div>

                <footer id="page-content">
                    <div class="footer-section">
                        <p>&copy; @settings.Value.Copyright</p>
                    </div>

                    <div class="footer-design">
                        <p>Developed By:</p>
                        <a href="@settings.Value.DeveloperSite">@settings.Value.Developer</a>
                    </div>
                </footer>
            </div>

        </div>
        

        @Html.Partial("_ApplicationScriptPartial")

        <!--Get root directory. Any js reference inside js file shoul append root directory to build complete valid path-->
       
        <script type="text/javascript">
            var deleteButtonDisplayName = "@Localizer[LabelConstants.Delete].Value";
            var editButtonDisplayName = "@Localizer[LabelConstants.Edit].Value";
            var resendButtonDisplayName = "@Localizer[LabelConstants.Resend].Value";
            var cancelButtonDisplayName = "@Localizer[LabelConstants.Cancel].Value";
            var saveButtonDisplayName = "@Localizer[LabelConstants.Save].Value";
            var rootDir = "@Url.Content("~/")";
            var languageFileUrl = "";
            $(document).ready(function () {
                var cultureInfo = $("#currentCultureName").val();
                switch (cultureInfo) {
                    case "fr-FR":
                        languageFileUrl = rootDir + "datatablelanguages/fr-FR.json";
                        break;
                    case "ne":
                        languageFileUrl = rootDir + "datatablelanguages/ne.json";
                        break;
                    case "de":
                        languageFileUrl = rootDir + "datatablelanguages/de.json";
                        break;
                    case "es-ES":
                        languageFileUrl = rootDir + "datatablelanguages/es-ES.json";
                        break;
                    case "ja":
                        languageFileUrl = rootDir + "datatablelanguages/ja.json";
                        break;
                    case "ko":
                        languageFileUrl = rootDir + "datatablelanguages/ko.json";
                        break;
                    case "zh-Hans":
                        languageFileUrl = rootDir + "datatablelanguages/zh-Hans.json";
                        break;
                    case "it-it":
                        languageFileUrl = rootDir + "datatablelanguages/it-it.json";
                        break;
                    default:
                        languageFileUrl = "";
                        break;
                }
            });

        </script>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

Lumle.Web/Views/Shared/_MessagePanel.cshtml
@if (TempData["SuccessMsg"] != null)
{
    <div class="alert alert-success" role="alert">@TempData["SuccessMsg"]</div>
}

@if (TempData["ErrorMsg"] != null)
{
    <div class="alert alert-danger" role="alert">@TempData["ErrorMsg"]</div>
}

@if (TempData["Info"] != null)
{
    <div class="alert alert-info" role="alert">@TempData["Info"]</div>
}
@if (TempData["EmailConfirmMsg"] != null)
{
    <div class="alert alert-success" role="alert">@TempData["EmailConfirmMsg"]</div>
}

Lumle.Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization
@using Lumle.Module.Localization.ViewModels
@using Lumle.Module.Localization.Services;

@inject ICultureService CultureService
@inject IViewLocalizer Localizer

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var data = CultureService.GetAll(x => x.IsEnable && x.IsActive)
                      .Select(c => new EnabledCultureListVM
                      {
                          Name = c.Name,
                          DisplayName = c.DisplayName
                      }).ToList();
}


<li class="dropdown language-dropdown">
    <a href="#" class="ropdown-toggle " data-toggle="dropdown">
        Language (@requestCulture.RequestCulture.UICulture.Name)
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu lang-selector">
        @foreach (var lang in data)
        {
            if (lang.Name == requestCulture.RequestCulture.UICulture.Name)
            {
                <li><a href="#" data-value="@lang.Name">@lang.DisplayName <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></a></li>
            }
            else
            {
                <li><a href="#" data-value="@lang.Name">@lang.DisplayName</a></li>
            }
        }
    </ul>
    <form asp-controller="Culture" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" id="lang-form" role="form">
        <input type="hidden" name="culture" value="@requestCulture.RequestCulture.UICulture.Name" />
    </form>
</li>

Lumle.Web/Views/Shared/_UserProfilePartial.cshtml
@using Lumle.Data.Models
@using Microsoft.AspNetCore.Identity

@inject UserManager<User> UserManager

<div class="user-account-btn dropdown custom_user">
    <a href="#" title="My Account" class="user-profile clearfix" data-toggle="dropdown">
        <img width="28" src="~/assets/image-resources/gravatar.png" alt="User Image">
        <span>@UserManager.GetUserName(User)!</span>
        <i class="glyph-icon icon-angle-down"></i>
    </a>
    <div class="dropdown-menu float-left">
        <div class="box-sm">
            <div class="login-box clearfix">
                <div class="user-img">
                    <img width="26" src="~/assets/image-resources/gravatar.png" style="background:#eee;">
                </div>
                <div class="user-info">
                    <a asp-controller="User" asp-action="Profile" title="Profile">@Localizer[LabelConstants.Profile]</a>
                    <a asp-controller="Manage" asp-action="ChangePassword" title="Change Password">@Localizer[LabelConstants.ChangePassword]</a>
                </div>
            </div>
            <form asp-action="LogOff" asp-controller="Account" method="post">
                <div class="pad5A button-pane button-pane-alt text-center">
                    <button type="submit" style="width: 100%" class="btn display-block font-normal btn-danger">
                        <i class="glyph-icon icon-power-off"></i>
                        @Localizer[LabelConstants.Logout]
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>