Modules/Lumle.Module.Authorization/Entities/Permission.cs
using Lumle.Data.Models;
using System.ComponentModel.DataAnnotations;

namespace Lumle.Module.Authorization.Entities
{
    public class Permission : EntityBase
    { 
        [Required]
        public string Slug { get; set; }

        [Required]
        public string DisplayName { get; set; }

        [Required]
        public string Menu { get; set; }

        public string SubMenu { get; set; }
    }
}

Modules/Lumle.Module.Authorization/Controllers/PermissionController.cs
using System;
using AutoMapper;
using Lumle.Module.Authorization.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Lumle.Core.Attributes;
using Lumle.Module.Authorization.ViewModels.PermissionViewModels;
using Lumle.Module.Authorization.Models;
using Lumle.Data.Data.Abstracts;
using Microsoft.AspNetCore.Authorization;
using Lumle.Infrastructure.Constants.AuthorizeRules;
using Lumle.Core.Services.Abstracts;
using System.Security.Claims;
using Lumle.Infrastructure.Constants.ActionConstants;
using System.Threading.Tasks;

namespace Lumle.Module.Authorization.Controllers
{
    [Route("authorization/[controller]")]
    [Authorize]
    public class PermissionController : Controller
    {
        private IRepository<Permission> _permissionRepository;
        private readonly IBaseRoleClaimService _baseRoleClaimService;

        public PermissionController(
            IRepository<Permission> permissionRepository,
            IBaseRoleClaimService baseRoleClaimService
        )
        {
            _permissionRepository = permissionRepository;
            _baseRoleClaimService = baseRoleClaimService;
        }

        [HttpGet]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionView)]
        public async Task<IActionResult> Index()
        {
            #region action-privelege
            // Make map to check for the action previleges
            var map = new Dictionary<string, Claim>
            {
                { OperationActionConstant.UpdateAction, new Claim("permission", Permissions.AuthorizationPermissionUpdate) }
            };

            // Get action previlege according to actions provided
            var actionClaimResult = await _baseRoleClaimService.GetActionPrevilegeAsync(map, User);
            #endregion

            var permissionEntities = _permissionRepository.GetAll();
            var permissions = Mapper.Map<IList<PermissionVM>>(permissionEntities);

            // Send permission edit previlege in view
            ViewBag.UpdateAction = actionClaimResult[OperationActionConstant.UpdateAction];

            return View(permissions);
        }


        [HttpGet("add")]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionCreate)]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("add")]
        [ValidateAntiForgeryToken]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionCreate)]
        public async Task<IActionResult> Add(PermissionVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["ErrorMsg"] = "Please fill the required field.";
                    return View(model);
                }

                var isSlugExist =
                   await _permissionRepository.GetSingleAsync(
                        x => string.Equals(x.Slug, model.Slug.Trim(), StringComparison.CurrentCultureIgnoreCase));

                if (isSlugExist != null)
                {
                    TempData["ErrorMsg"] = "Permission already exist. Try with new slug.";
                    return View(model);
                }

                var permissionModel = SplitSlug(model);
                var permissionEntity = Mapper.Map<Permission>(permissionModel);

                await _permissionRepository.AddAsync(permissionEntity);

                TempData["SuccessMsg"] = "Permission added successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["ErrorMsg"] = "Error Occured. Please try again.";
                return RedirectToAction("Index");
            }
        }

        [HttpGet("edit/{id:int}")]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionUpdate)]
        public async Task<IActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                TempData["ErrorMsg"] = "Permission not found.";
                return RedirectToAction("Index");
            }

            var permissionEntity = await _permissionRepository.GetSingleAsync(x => x.Id == id);
            if (permissionEntity == null)
            {
                TempData["ErrorMsg"] = "Permission not found.";
                return RedirectToAction("Index");
            }

            var permission = Mapper.Map<PermissionVM>(permissionEntity);

            return View(permission);
        }

        [HttpPost("edit/{id:int}")]
        [ValidateAntiForgeryToken]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionUpdate)]
        public async Task<IActionResult> Edit(PermissionVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    TempData["ErrorMsg"] = "Please fill the required field.";
                    return View(model);
                }

                var permission = await _permissionRepository.GetSingleAsync(x => x.Id == model.Id);
                if (permission == null)
                {
                    TempData["ErrorMsg"] = "Permission does not exist.";
                    return View("Edit", model);
                }

                var permissionModel = SplitSlug(model);
                var permissionEntity = Mapper.Map<Permission>(permissionModel);
                permissionEntity.Id = model.Id;

                await _permissionRepository.UpdateAsync(permissionEntity, permissionEntity.Id);

                TempData["SuccessMsg"] = "Permission updated successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["ErrorMsg"] = "Error Occured. Please try again.";
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost("delete/{id:int}")]
        [ValidateAntiForgeryToken]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.AuthorizationPermissionDelete)]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                if (id <= 0)
                {
                    TempData["ErrorMsg"] = "Permission not found.";
                    return RedirectToAction("Index");
                }

                var permission = await _permissionRepository.GetSingleAsync(x => x.Id == id);
                if (permission == null)
                {
                    TempData["ErrorMsg"] = "Permission not found.";
                    return RedirectToAction("Index");
                }

                _permissionRepository.DeleteWhere(x => x.Id == id);

                TempData["SuccessMsg"] = "Permission deleted successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["ErrorMsg"] = "Error Occured. Please try again.";
                return RedirectToAction("Index");
            }
        }

        #region Helper Class
        private static PermissionModel SplitSlug(PermissionVM model)
        {
            var slugArray = model.Slug.Split('.');
            var permission = new PermissionModel
            {
                Slug = model.Slug.Trim().ToLower(),
                DisplayName = model.DisplayName.Trim(),
                Menu = slugArray[0].Trim().ToLower(),
                SubMenu = slugArray.Length > 1 ? slugArray[1].Trim().ToLower() : string.Empty,
                CreatedDate = DateTime.UtcNow
            };

            return permission;
        }
        #endregion
    }
}

Modules/Lumle.Module.Authorization/Views/Permission/Edit.cshtml
@using Lumle.Module.Authorization.ViewModels.PermissionViewModels
@model PermissionVM

@{
    ViewData["Title"] = "Edit Permission";
}

<div class="breadcrumb-section clearfix">
    <ol class="breadcrumb">
        <li class="module">Authorization</li>
        <li><a asp-action="Index" asp-controller="Permission">Permissions</a></li>
        <li class="active">Edit Permission</li>
    </ol>
</div>

@Html.Partial("_MessagePanel")

<div class="panel">
    <h3 class="title-hero title-setting"> Edit Permission </h3>
    <div class="panel-body custom-panel">
        <div class="example-box-wrapper">
            <form id="mainForm" class="form-horizontal bordered-row" asp-action="EditPermission" method="post" data-parsley-validate novalidate>
                <div class="row">
                    <div class="col-md-12 main-section">
                        @Html.HiddenFor(x => x.Id)

                        <div class="form-group" style="border-top: 0;">
                            <label class="col-sm-3 control-label">Slug <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input asp-for="Slug" type="text" required class="form-control">
                            </div>
                        </div>
                        <div class="form-group form-section">
                            <label class="col-sm-3 control-label">Display Name <span class="text-danger">*</span></label>
                            <div class="col-sm-6">
                                <input type="text" asp-for="DisplayName" required class="form-control" id="">
                            </div>
                        </div>

                        <div class="form-group form-section">
                            <div class="col-sm-9">
                                <div class="pull-right">
                                    <a class="btn btn-default btn-cancel btn-sm" asp-action="Index">Cancel</a>
                                    <button type="submit" class="btn btn-success custom-btn btn-sm">Save Changes</button>
                                    <img id="loadingImg" style="width: 30px; display:none;" src="~/assets/images/spinner/loader-dark.gif" alt="loading image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/assets/widgets/parsley/parsley.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#mainForm').on('submit', function () {
                var form = $(this);
                form.parsley().validate();
                var isValidForm = form.parsley().isValid();
                if (isValidForm) {
                    form.find('button[type=submit]').prop('disabled', true);
                    $("#loadingImg").show();
                    form.get(0).submit();
                }
                return false;
            });
        });
    </script>
}

Modules/Lumle.Module.Authorization/Views/Permission/Index.cshtml
@using Lumle.Module.Authorization.ViewModels.PermissionViewModels
@model List<PermissionVM>

@{   
    var updateAction = ViewBag.UpdateAction;

    ViewData["Title"] = "Permission";
}

@section styles{
    <link rel="stylesheet" type="text/css" href="~/assets/widgets/datatable/datatable.css">
}

<div class="row">
    <div id="page-title">
        <h2 class="display-inline">Permissions</h2>
    </div>
    <div class="breadcrumb-section clearfix">
        <ol class="breadcrumb">
            <li class="module">Authorization</li>
            <li class="active">Permissions</li>
        </ol>
    </div>

    @Html.Partial("_MessagePanel")

    <div class="panel">
        <div class="panel-body">
            <div class="dataTable">
                <table id="permissionTable" class="table">
                    <thead>
                        <tr>
                            <th>Slug</th>
                            <th>Display Name</th>
                            @if (updateAction)
                            {
                                <th>Action</th>
                            }
                        </tr>
                    </thead>
                    <tbody>

                        @for (var i = 0; i < Model.Count; i++)
                        {
                            <tr>
                                <td>@Model[i].Slug</td>
                                <td>@Model[i].DisplayName</td>
                                @if (updateAction)
                                {
                                    <td>
                                        <a id="editPermission" href="~/authorization/permission/edit/@Model[i].Id"
                                           class="btn btn-info btn-xs">
                                            <i class="glyph-icon icon-pencil"></i> Edit
                                        </a>
                                    </td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable.min.js"></script>
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable-bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable-responsive.min.js"></script>
    <script src="~/js/authorization-permission-index.js" asp-append-version="true"></script>
}