Modules/Lumle.Module.Localization/ViewModels/CultureViewModel.cs
namespace Lumle.Module.Localization.ViewModels
{
    public class CultureViewModel
    {
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}

Modules/Lumle.Module.Localization/Controllers/CultureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lumle.Core.Attributes;
using Lumle.Core.Localizer;
using Lumle.Core.Models;
using Lumle.Data.Data.Abstracts;
using Lumle.Data.Models;
using Lumle.Infrastructure.Constants.AuthorizeRules;
using Lumle.Infrastructure.Constants.LumleLog;
using Lumle.Module.Audit.Enums;
using Lumle.Module.Audit.Models;
using Lumle.Module.Audit.Services;
using Lumle.Module.Localization.Helpers;
using Lumle.Module.Localization.Models;
using Lumle.Module.Localization.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using NLog;
using Microsoft.Extensions.Localization;
using Lumle.Module.Localization.ViewModels;
using Lumle.Infrastructure.Constants.Localization;
using OfficeOpenXml;
using System.IO;
using Lumle.Infrastructure.Constants.Cache;
using Lumle.Core.Services.Abstracts;
using System.Security.Claims;
using Lumle.Infrastructure.Constants.ActionConstants;

namespace Lumle.Module.Localization.Controllers
{
    [Route("localization/[Controller]")]
    [Authorize]
    public class CultureController : Controller
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        private readonly IBaseRoleClaimService _baseRoleClaimService;
        private readonly ICultureService _cultureService;
        private readonly IResourceService _resourceService;
        private readonly IMemoryCache _memoryCache;
        private readonly IAuditLogService _auditLogService;
        private readonly UserManager<User> _userManager;
        private readonly IStringLocalizer<ResourceString> _localizer;
        private IList<ResourceString> _resourceStrings;
        private readonly IRepository<Resource> _resourceRepository;

        public CultureController(
            IBaseRoleClaimService baseRoleClaimService,
            ICultureService cultureService,
            IResourceService resourceService,
            IMemoryCache memoryCache,
            IAuditLogService auditLogService,
            UserManager<User> userManager,
            IStringLocalizer<ResourceString> localizer,
            IRepository<Resource> resourceRepository
        )
        {
            _baseRoleClaimService = baseRoleClaimService;
            _userManager = userManager;
            _cultureService = cultureService;
            _resourceService = resourceService;
            _memoryCache = memoryCache;
            _auditLogService = auditLogService;
            _localizer = localizer;
            _resourceRepository = resourceRepository;
        }

        [HttpPost("setlanguage")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetLanguage(string culture, string returnUrl)
        {
            try
            {
                if (string.IsNullOrEmpty(culture) && string.IsNullOrWhiteSpace(culture)) return LocalRedirect(returnUrl);

                var supportedCulture = _cultureService.GetAll(x => x.Name == culture.Trim());
                if (supportedCulture == null) return LocalRedirect(returnUrl);

                Response.Cookies.Append(
                    CookieRequestCultureProvider.DefaultCookieName,
                    CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                    new CookieOptions { Expires = DateTime.UtcNow.AddYears(1) }
                    );

                var user = await _userManager.GetUserAsync(HttpContext.User);
                user.Culture = culture.Trim();
                await _userManager.UpdateAsync(user);

                ReloadLocalizationResourceCache(culture.Trim());

                return LocalRedirect(returnUrl);
            }
            catch (Exception ex)
            {
                Logger.Error(ex, ErrorLog.Undefinederror);
                return LocalRedirect(returnUrl);
            }

        }

        [HttpGet]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.LocalizationCultureView)]
        public async Task<IActionResult> Index()
        {
            #region action-privelege
            // Make map to check for the action previleges
            var map = new Dictionary<string, Claim>
            {
                { OperationActionConstant.CreateAction, new Claim("permission", Permissions.LocalizationCultureCreate) }
            };

            // Get action previlege according to actions provided
            var actionClaimResult = await _baseRoleClaimService.GetActionPrevilegeAsync(map, User);
            #endregion

            var cultures = _cultureService.GetAllCulture();

            // Get inactive cultures
            var inActiveCultures = cultures.Where(x => !x.IsEnable).ToList();

            // Get enabled cultures
            var enabledCultures = cultures.Where(x => x.IsEnable).ToList();

            var cultureListVm = new CultureListVM
            {
                EnabledCultures = enabledCultures,
                InActiveCultures = inActiveCultures,
                InActiveCultureCount = inActiveCultures.Count,
                CreateAction = actionClaimResult[OperationActionConstant.CreateAction]
            };

            return View(cultureListVm);
        }

        [HttpGet("{culture}")]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.LocalizationCultureView)]
        public async Task<IActionResult> Resource(string culture)
        {
            #region action-privelege
            // Make map to check for the action previleges
            var map = new Dictionary<string, Claim>
            {
                { OperationActionConstant.UpdateAction, new Claim("permission", Permissions.LocalizationCultureUpdate) }
            };

            // Get action previlege according to actions provided
            var actionClaimResult = await _baseRoleClaimService.GetActionPrevilegeAsync(map, User);
            #endregion

            var model = new ImportResourceModel { Culture = culture };

            // Send permission edit previlege in view
            ViewBag.UpdateAction = actionClaimResult[OperationActionConstant.UpdateAction];

            return View("Resource", model);
        }

        [HttpPost("addorupdateresource")]
        [ValidateAntiForgeryToken]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.LocalizationCultureUpdate)]
        public async Task<JsonResult> AddOrUpdateResource([FromBody] ResourceModel resource)
        {
            try
            {
                var loggedUser = await GetCurrentUserAsync(); //Get current logged in user

                await _resourceService.CreateResource(resource, loggedUser);

                ReloadLocalizationResourceCache(loggedUser.Culture);
                return Json(new { success = true, messageTitle = _localizer[ActionMessageConstants.UpdatedSuccessfully].Value, message = _localizer[ActionMessageConstants.UpdatedSuccessfully].Value });

            }
            catch (Exception ex)
            {
                Logger.Error(ex, ErrorLog.AddUpdateError);
                return Json(new { success = false, messageTitle = _localizer[ActionMessageConstants.ErrorOccured].Value, message = _localizer[ActionMessageConstants.InternalServerErrorMessage].Value });
            }
        }

        [HttpPost("new")]
        [ValidateAntiForgeryToken]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.LocalizationCultureCreate)]
        public async Task<IActionResult> AddNewCulture(string selectedCulture)
        {
            try
            {
                var loggedUser = await GetCurrentUserAsync(); //Get current logged user

                if (string.IsNullOrEmpty(selectedCulture) || string.IsNullOrWhiteSpace(selectedCulture))
                {
                    TempData["ErrorMsg"] = _localizer[ActionMessageConstants.SelectValidItemErrorMessage].Value;
                    return RedirectToAction("Index");
                }
                var culture = await _cultureService.GetSingle(x => x.Name == selectedCulture.Trim() && !x.IsEnable);

                if (culture == null)
                {
                    TempData["ErrorMsg"] = _localizer[ActionMessageConstants.ResourceNotFoundErrorMessage].Value;
                    return RedirectToAction("Index");
                }

                await _cultureService.CreateResource(loggedUser, culture);

                _memoryCache.Remove(CacheConstants.LocalizationCultureCache);
                TempData["SuccessMsg"] = _localizer[ActionMessageConstants.AddedSuccessfully].Value;
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Logger.Error(ex, ErrorLog.SaveError);
                return RedirectToAction("Index");
            }
        }

        [HttpPost("updateCulture")]
        [ClaimRequirement(CustomClaimtypes.Permission, Permissions.LocalizationCultureUpdate)]
        public async Task<IActionResult> UpdateCulture([FromBody] CultureViewModel cultureViewModel)
        {
            try
            {
                if (cultureViewModel.Name == DefaultCultureConstants.DefaultCultureName) return Json(new { success = false, messageTitle = _localizer[ActionMessageConstants.ErrorOccured].Value, message = _localizer[ActionMessageConstants.InternalServerErrorMessage].Value });

                var culture = await _cultureService.GetSingle(x => x.IsEnable && x.Name == cultureViewModel.Name.Trim());
                if (culture == null)
                {
                    return Json(new { success = false, messageTitle = _localizer[ActionMessageConstants.ErrorOccured].Value, message = _localizer[ActionMessageConstants.ResourceNotFoundErrorMessage].Value });
                }
                _memoryCache.Remove(CacheConstants.LocalizationCultureCache);

Modules/Lumle.Module.Localization/Views/Culture/Index.cshtml
@using Lumle.Module.Localization.ViewModels
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@model CultureListVM

@{
    ViewData["Title"] = Localizer[LabelConstants.Culture];
    var antiforgeryRequestToken = antiforgery.GetAndStoreTokens(Context).RequestToken;
}

@section styles
{
    <link href="~/assets/widgets/datatable/datatable.min.css" type="text/css" rel="stylesheet" />
    <link href="~/assets/widgets/input-switch/inputswitch-alt.min.css" type="text/css" rel="stylesheet" />
    <link href="~/lib/toastr/toastr.css" type="text/css" rel="stylesheet" />
    <style type="text/css">
        div.switch-toggle { left: 110px; }
    </style>
}

<div id="page-title">
    <h2 class="display-inline">@Localizer[LabelConstants.Localization]</h2>

    @if (Model.CreateAction)
    {
        @if (Model.InActiveCultureCount > 0)
        {
            <button class="btn btn-primary btn-sm pull-right" data-toggle="modal" data-target="#addLanguageModal">
                <i class="glyph-icon icon-plus"></i>  @Localizer[LabelConstants.AddNew]
            </button>
        }
    }
</div>

<div class="breadcrumb-section clearfix">
    <ol class="breadcrumb">
        <li class="module">@Localizer[LabelConstants.Localization]</li>
        <li class="active">@Localizer[LabelConstants.Culture]</li>
    </ol>
</div>

@Html.Partial("_MessagePanel")

<div class="example-box-wrapper">

    <div class="modal fade" id="addLanguageModal" tabindex="-1" role="dialog" aria-labelledby="addLanguageModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <form asp-action="AddNewCulture" method="post" role="form" class="form-horizontal">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">@Localizer[LabelConstants.AddNew]</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">@Localizer[LabelConstants.SelectLanguage]</label>
                            <div class="col-sm-6">
                                <select class="form-control" name="selectedCulture" required>
                                    <option value="" selected>@Localizer[LabelConstants.PleaseSelect]</option>

                                    @for (int i = 0; i < Model.InActiveCultureCount; i++)
                                    {
                                        <option value="@Model.InActiveCultures[i].Name">@Model.InActiveCultures[i].DisplayName</option>

                                    }
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">@Localizer[LabelConstants.Cancel]</button>
                        <button type="submit" class="btn btn-success btn-sm">@Localizer[LabelConstants.Save]</button>
                        <img id="loadingImg" style="width: 30px; display:none;" src="~/assets/images/spinner/loader-dark.gif" alt="loading image">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-body">
        <div class="dataTable">
            <table cellpadding="0" cellspacing="0" border="0" class="table" id="cultureDataTable">
                <thead>
                    <tr>
                        <th>@Localizer[LabelConstants.SN]</th>
                        <th>@Localizer[LabelConstants.Language]</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>

                    @for (int i = 0; i < Model.EnabledCultures.Count; i++)
                    {
                        <tr>
                            <td>@Model.EnabledCultures[i].Sn</td>
                            <td>@Model.EnabledCultures[i].DisplayName</td>
                            <td>
                                <div class="form-group ">
                                    <a class="btn btn-info btn-xs display-inline" style="float:left;" href="~/localization/culture/@Model.EnabledCultures[i].Name"><i class="glyph-icon icon-cog"></i> @Localizer[LabelConstants.Manage]</a>
                                    @if (Model.EnabledCultures[i].Name != "en-US")
                                    {
                                        if (Model.EnabledCultures[i].IsActive)
                                        {
                                            <div class="switch-toggle switch-on" value="@Model.EnabledCultures[i].Name"></div>
                                        }
                                        else
                                        {
                                            <div class="switch-toggle switch-off" value="@Model.EnabledCultures[i].Name"></div>
                                        }
                                    }
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script type="text/javascript">
        var token = @Json.Serialize(antiforgeryRequestToken);
    </script>

    <script src="~/lib/toastr/toastr.min.js"></script>
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable.min.js"></script>
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable-bootstrap.min.js"></script>
    <script type="text/javascript" src="~/assets/widgets/datatable/datatable-responsive.min.js"></script>
    <script src="~/assets/widgets/datatable/datatable-tabletools.js"></script>
    <script src="~/js/localization-index-datatable.js"></script>
}

Modules/Lumle.Module.Localization/Views/Culture/Resource.cshtml
@using System.Globalization;
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery antiforgery

@model ImportResourceModel

@{
    ViewData["Title"] = Localizer[LabelConstants.Resource];
    var antiforgeryRequestToken = antiforgery.GetAndStoreTokens(Context).RequestToken;
    var cultureName = new CultureInfo(Model.Culture).DisplayName;
    var hasPermissionForUpdate = ViewBag.UpdateAction;
}

@section styles
    {
    <link href="~/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="~/assets/widgets/datatable/datatable.min.css">
    <link href="~/lib/toastr/toastr.css" rel="stylesheet" />
}

<div id="page-title">
    <h2 class="display-inline">@Localizer[LabelConstants.Localization]</h2>
</div>

<div class="breadcrumb-section clearfix">
    <ol class="breadcrumb">
        <li class="module">@Localizer[LabelConstants.Localization]</li>
        <li><a href="~/localization/culture">@Localizer[LabelConstants.Culture]</a></li>
        <li class="active">@Localizer[LabelConstants.Resource]</li>
    </ol>
</div>

<label id="lblCulture" hidden="hidden" value="@Model.Culture"></label>
@Html.Partial("_MessagePanel")
<div class="panel">
    <div class="panel-body">
        <div class="row">
            <div class="form-group">
                <h5 class="control-label col-md-3">
                    @cultureName
                </h5>
                <label class="control-label col-sm-1">@Localizer[LabelConstants.FilterBy]</label>
                <div class="col-md-4">
                    <select class="form-control" id="resourceFilterBy">
                        <option value="0" selected>@Localizer[LabelConstants.All]</option>
                        <option value="1">@Localizer[LabelConstants.Label]</option>
                        <option value="2">@Localizer[LabelConstants.Message]</option>
                    </select>
                </div>
                <div class="pull-right">
                    <a href="#" title="Import Excel" class="user-profile clearfix" style="text-decoration: none;" data-toggle="modal" data-target="#importExcelModel">
                        <i class="glyph-icon icon-arrow-circle-up"></i>
                        <span>@Localizer[LabelConstants.ImportExcel]</span>
                    </a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="dataTable">
                <table class="table" id="resourceDataTable" style="width:100% !important;">
                    <thead>
                        <tr>
                            <th>@Localizer[LabelConstants.SN]</th>
                            <th></th>
                            <th></th>
                            <th>@Localizer[LabelConstants.OriginalWord]</th>
                            <th>@Localizer[LabelConstants.TranslatedWord]</th>
                            <th>@Localizer[LabelConstants.Action]</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!--Modal section-->
<div id="importExcelModel" class="modal fade in" tabindex="-1" role="dialog" aria-hidden="true" style="padding-right:0px;">
    <div class="modal-dialog" style="margin-top:10% !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <h3 class="modal-title">@Localizer[LabelConstants.ImportDataFromExcel]</h3>
            </div>
            <form method="post" enctype="multipart/form-data" asp-controller="Culture" asp-action="ImportExcel" asp-route-resourcetype="">
                <div class="modal-body">
                    <input type="hidden" asp-for="Culture" />
                    <h5 class="control-label">@Localizer[LabelConstants.Language] : <span>@cultureName</span></h5>
                    <div class="form-group">
                        <h5 class="control-label">@Localizer[LabelConstants.ResourceType] </h5>
                        <select id="resourceType" asp-for="ResourceCategoryId" class="form-control">
                            <option value="1">@Localizer[LabelConstants.Label]</option>
                            <option value="2">@Localizer[LabelConstants.Message]</option>
                        </select>
                    </div>
                    <p class="alert alert-notice">@Localizer[LabelConstants.ExcelSheetFormatMessageForResourceImport]</p>
                    <h5 class="control-label">@Localizer[LabelConstants.ChooseExcelFilestoImportData]</h5>
                    <input type="file" class="form-control" name="files" asp-for="Files" multiple accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" />
                </div>
                <div class="modal-footer">
                    <button data-dismiss="modal" class="btn btn-default" type="button">@Localizer[LabelConstants.Cancel]</button>
                    <input type="submit" id="btnSubmit" class="btn btn-success" value=@Localizer[LabelConstants.Submit] disabled />
                    <img id="loadingImg" style="width: 30px; display:none;" src="~/assets/images/spinner/loader-dark.gif" alt="loading image">
                </div>
            </form>
        </div>
    </div>
</div>
@section scripts
{
    <script type="text/javascript">
        var token = @Json.Serialize(antiforgeryRequestToken);
        var hasPermissionForUpdateResource=@hasPermissionForUpdate.ToString().ToLower();
    </script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="~/js/dataTables.bootstrap.min.js"></script>
    <script src="~/js/localization-resource-datatable.js"></script>

}